#!/usr/bin/env python
"""Diff two probe files (from api_diff.py) into a Markdown report.

    python probes/diff_report.py probes/results/probe_4.14.0.json \
        probes/results/probe_5.0.0.json --out probes/results/diff_4.14_vs_5.0.md

Buckets:
  * behaviour changes: ok <-> raised, or a different observation (the curriculum)
  * error-text changes: raised in both, with different (normalised) messages
  * unchanged
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

CATEGORY_ORDER = ["existence", "shapes", "pixels", "gotchas"]


def load_arrays(json_path: Path) -> dict:
    npz = json_path.with_suffix(".npz")
    return dict(np.load(npz)) if npz.exists() else {}


def magnitude(a: np.ndarray | None, b: np.ndarray | None) -> str:
    """How big is a pixel-level change? (max |Δ| and the fraction of elements that moved)"""
    if a is None or b is None or a.shape != b.shape:
        return ""
    d = np.abs(a.astype(np.float64) - b.astype(np.float64))
    return f"max abs diff {d.max():g}, {100 * np.mean(d > 0):.1f}% of values differ"


def cell(rec: dict | None, width: int = 110) -> str:
    if rec is None:
        return "(not probed)"
    if rec["ok"]:
        text = json.dumps(rec["obs"], separators=(", ", ": "))
    else:
        text = "raises " + rec["error"]
    if len(text) > width:
        text = text[: width - 1] + "…"
    return "`" + text.replace("|", "\\|").replace("`", "'") + "`"


def same(a: dict, b: dict) -> bool:
    return a["ok"] == b["ok"] and (a.get("obs") == b.get("obs") if a["ok"] else True)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("old", type=Path)
    ap.add_argument("new", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    old, new = json.loads(args.old.read_text()), json.loads(args.new.read_text())
    arrays_old, arrays_new = load_arrays(args.old), load_arrays(args.new)
    vo, vn = old["env"]["cv2"], new["env"]["cv2"]
    names = list(dict.fromkeys([*old["probes"], *new["probes"]]))

    changed, err_text, unchanged = [], [], []
    for n in names:
        a, b = old["probes"].get(n), new["probes"].get(n)
        if a is None or b is None or not same(a, b):
            changed.append(n)
        elif not a["ok"] and a["error"] != b["error"]:
            err_text.append(n)
        else:
            unchanged.append(n)

    def rec(n):
        return old["probes"].get(n) or new["probes"][n]

    lines = [
        f"# OpenCV {vo} → {vn}: measured API diff",
        "",
        f"Generated by `probes/diff_report.py` from `{args.old.name}` and `{args.new.name}` "
        f"(headless wheels, numpy {new['env']['numpy']}, Python {new['env']['python']}, "
        f"{new['env']['platform']}). Every cell is an observation, not documentation: "
        "re-run `probes/api_diff.py` in each environment to reproduce.",
        "",
        f"**{len(names)} probes: {len(changed)} behaviour changes, "
        f"{len(err_text)} error-text-only changes, {len(unchanged)} unchanged.**",
        "",
        "## Behaviour changes (the fine-tuning curriculum)",
        "",
    ]
    for cat in CATEGORY_ORDER:
        rows = [n for n in changed if rec(n)["category"] == cat]
        if not rows:
            continue
        lines += [f"### {cat} ({len(rows)})", "",
                  f"| probe | {vo} | {vn} | idiom at risk |", "|---|---|---|---|"]
        for n in rows:
            notes = [rec(n)["idiom"], magnitude(arrays_old.get(n), arrays_new.get(n))]
            idiom = "; ".join(x for x in notes if x).replace("|", "\\|")
            lines.append(f"| `{n}` | {cell(old['probes'].get(n))} | {cell(new['probes'].get(n))} | {idiom} |")
        lines.append("")

    if err_text:
        lines += ["## Raises in both, different message", "",
                  "Same failure, different wording. Matters only for repair prompts that quote errors.", "",
                  f"| probe | {vo} | {vn} |", "|---|---|---|"]
        lines += [f"| `{n}` | {cell(old['probes'][n], 90)} | {cell(new['probes'][n], 90)} |" for n in err_text]
        lines.append("")

    timeless = [n for n in unchanged if rec(n)["category"] == "gotchas"]
    if timeless:
        lines += ["## Timeless gotchas (same in both versions)", "",
                  "Seed rows for the gotcha suite: behaviour a model must get right on any version.", "",
                  f"| probe | observed ({vn}) | idiom at risk |", "|---|---|---|"]
        for n in timeless:
            lines.append(f"| `{n}` | {cell(new['probes'][n], 120)} | {rec(n)['idiom'].replace('|', chr(92) + '|')} |")
        lines.append("")

    lines += ["## Unchanged", "", "<details><summary>"
              f"{len(unchanged)} probes behave identically</summary>", ""]
    for cat in CATEGORY_ORDER:
        rows = [n for n in unchanged if rec(n)["category"] == cat]
        if not rows or cat == "gotchas":  # gotchas already listed with their outcomes above
            continue
        if cat == "existence":  # a shared False is as informative as a shared True
            for label, val in (("present in both", True), ("absent in both", False)):
                group = [n for n in rows if rec(n).get("obs") is val]
                if group:
                    lines.append(f"- **existence, {label}**: " + ", ".join(f"`{n}`" for n in group))
            rest = [n for n in rows if not isinstance(rec(n).get("obs"), bool)]
            if rest:
                lines.append("- **existence, other**: " + ", ".join(f"`{n}`" for n in rest))
        else:
            lines.append(f"- **{cat}**: " + ", ".join(f"`{n}`" for n in rows))
    lines += ["", "</details>", ""]

    args.out.write_text("\n".join(lines))
    print(f"{len(changed)} behaviour changes, {len(err_text)} error-text changes, "
          f"{len(unchanged)} unchanged -> {args.out}")


if __name__ == "__main__":
    main()
